stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: '20.11.0'

.install_deps:
  before_script:
    - npm ci

build:
  stage: build
  image: node:${NODE_VERSION}
  extends: .install_deps
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

deploy_vercel:
  stage: deploy
  image: node:${NODE_VERSION}
  extends: .install_deps
  script:
    - npm install -g vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
  only:
    - main
