name = "bluesky-card-cast"
compatibility_date = "2026-02-23"
compatibility_flags = ["nodejs_compat"]
account_id = "3086a7566da7a09d7d7d74a6ec48b5fc"
# Wrangler v4 doesn't support the `type` field or `build.upload` in the same way.
workers_dev = true

[vars]
EXTENSION_SHARED_SECRET= "${EXTENSION_SHARED_SECRET}"

ENVIRONMENT = "production"

# Main entry point for the Worker (built artifact)
main = "cf-worker.js"

# Your actual static assets directory
[assets]
directory = "./extension/dist-extension"

[vars]
EXTENSION_SHARED_SECRET = "${EXTENSION_SHARED_SECRET}"
