/**
 * @fileoverview Generates extension config file from environment variables.
 * This script reads environment variables and creates a config file that
 * can be imported by the extension code.
 *
 * It will:
 * 1. Check for environment variables in process.env
 * 2. Optionally read from extension/.env file if it exists
 * 3. Use defaults if neither is available
 */

const fs = require('fs');
const path = require('path');

// Try to load .env file if it exists
const envPath = path.join(__dirname, '../.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach((line) => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim();
        // Remove quotes if present and trim again
        const cleanValue = value.replace(/^["']|["']$/g, '').trim();
        if (!process.env[key.trim()]) {
          process.env[key.trim()] = cleanValue;
        }
      }
    }
  });
}

// Read environment variables (from process.env or .env file)
const BACKEND_URL =
  (process.env.NEXT_PUBLIC_BACKEND_URL || '').trim() ||
  'https://bluesky-card-cast-extension-8u6iubpsm-chejholloway1s-projects.vercel.app';

const EXTENSION_SHARED_SECRET =
  (process.env.EXTENSION_SHARED_SECRET || '').trim() ||
  'REPLACE_WITH_REAL_SECRET';

// Generate config file content
const configContent = `/**
 * @fileoverview Extension configuration generated from environment variables.
 * 
 * This file is auto-generated by scripts/generate-config.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To update these values:
 * 1. Set environment variables: NEXT_PUBLIC_BACKEND_URL and EXTENSION_SHARED_SECRET
 * 2. Run: npm run build:ext
 */

/** Backend URL for API requests */
export const BACKEND_URL = '${BACKEND_URL}';

/** Shared secret for authenticating extension requests */
export const EXTENSION_SHARED_SECRET = '${EXTENSION_SHARED_SECRET}';
`;

// Write config file
const configPath = path.join(__dirname, '../src/config.ts');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Extension config generated successfully');
console.log(`   Backend URL: ${BACKEND_URL}`);
console.log(`   Secret: ${EXTENSION_SHARED_SECRET.substring(0, 10)}...`);
