/**
 * @fileoverview Generates extension config file from environment variables.
 * This script reads environment variables and creates a config file that
 * can be imported by the extension code.
 *
 * It will:
 * 1. Check for environment variables in process.env
 * 2. Optionally read from extension/.env file if it exists
 * 3. Use defaults if neither is available
 */

const fs = require('fs');
const path = require('path');

// Try to load .env file if it exists
const envPath = path.join(__dirname, '../.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach((line) => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim();
        // Remove quotes if present and trim again
        const cleanValue = value.replace(/^["']|["']$/g, '').trim();
        if (!process.env[key.trim()]) {
          process.env[key.trim()] = cleanValue;
        }
      }
    }
  });
}

// Read environment variables (from process.env or .env file)
const BACKEND_URL =
  (process.env.NEXT_PUBLIC_BACKEND_URL || '').trim() ||
  'https://bluesky-card-cast-extension-8u6iubpsm-chejholloway1s-projects.vercel.app';

const EXTENSION_SHARED_SECRET =
  (process.env.EXTENSION_SHARED_SECRET || '').trim() ||
  'REPLACE_WITH_REAL_SECRET';

// List of assets to ensure present in both dist outputs (src and legacy)
const assets = [
  'background.js',
  'contentScript.js',
  'popup.js',
  'popup.html',
  'manifest.json',
  'config.js',
  'trpcClient.js',
  'types.js',
  path.join('icons', 'icon-16.png'),
  path.join('icons', 'icon-32.png'),
  path.join('icons', 'icon-48.png'),
  path.join('icons', 'icon-128.png'),
  path.join('icons', 'icon-256.png'),
  path.join('icons', 'icon-512.png'),
];

// Generate config file content
const configContent = `/**
 * @fileoverview Extension configuration generated from environment variables.
 * 
 * This file is auto-generated by scripts/generate-config.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To update these values:
 * 1. Set environment variables: NEXT_PUBLIC_BACKEND_URL and EXTENSION_SHARED_SECRET
 * 2. Run: npm run build:ext
 */

/** Backend URL for API requests */
export const BACKEND_URL = '${BACKEND_URL}';

/** Shared secret for authenticating extension requests */
export const EXTENSION_SHARED_SECRET = '${EXTENSION_SHARED_SECRET}';
`;

// Write config file
const configPath = path.join(__dirname, '../src/config.ts');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Extension config generated successfully');
console.log('   Backend URL: [redacted]');
console.log('   Secret: [redacted]');

// After generating the in-tree config, also propagate necessary extension assets
// to build outputs to ensure Chrome can load the extension from either
// src/extension/dist or a legacy extension/dist location if present.
try {
  const destRootSrc = path.join(
    __dirname,
    '..',
    '..',
    'src',
    'extension',
    'dist'
  );
  const destRootLegacy = path.join(__dirname, '..', '..', 'extension', 'dist');
  const ensureDir = (p) => {
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
  };
  ensureDir(destRootSrc);
  ensureDir(destRootLegacy);

  const copyTo = (src, dst) => {
    if (fs.existsSync(src)) {
      ensureDir(path.dirname(dst));
      fs.copyFileSync(src, dst);
    }
  };

  // Copy an asset from the most relevant build location to both destinations
  const copyAssetToDests = (relPath) => {
    const candidates = [
      path.join(__dirname, '..', '..', 'src', 'extension', 'dist', relPath),
      path.join(__dirname, '..', '..', 'extension', 'dist', relPath),
      path.join(__dirname, '..', relPath),
    ];
    for (const src of candidates) {
      if (fs.existsSync(src)) {
        const dstSrc = path.join(destRootSrc, relPath);
        const dstLegacy = path.join(destRootLegacy, relPath);
        ensureDir(path.dirname(dstSrc));
        ensureDir(path.dirname(dstLegacy));
        fs.copyFileSync(src, dstSrc);
        fs.copyFileSync(src, dstLegacy);
        return;
      }
    }
    console.warn(`Asset missing in all candidates: ${relPath}`);
  };

  // Copy manifest to both destinations (via asset resolver)
  copyAssetToDests('manifest.json');

  // Copy icons to both destinations
  const iconsSrcDir = path.join(__dirname, '..', 'icons');
  if (fs.existsSync(iconsSrcDir)) {
    fs.readdirSync(iconsSrcDir).forEach((fname) => {
      const rel = path.join('icons', fname);
      copyAssetToDests(rel);
    });
  }

  // Copy all remaining assets to both destinations, ensuring background.js,
  // contentScript.js, popup.js, etc. are present in both output dirs.
  assets.forEach((rel) => {
    copyAssetToDests(rel);
  });

  // Copy popup.html to both destinations
  const popupSrcPrimary = path.join(__dirname, '..', 'src', 'popup.html');
  const popupSrcFallback = path.join(
    __dirname,
    '..',
    'extension',
    'src',
    'popup.html'
  );
  const popupSrcList = [popupSrcPrimary, popupSrcFallback];
  let copiedPopup = false;
  for (const p of popupSrcList) {
    if (fs.existsSync(p)) {
      copyTo(p, path.join(destRootSrc, 'popup.html'));
      copyTo(p, path.join(destRootLegacy, 'popup.html'));
      copiedPopup = true;
      break;
    }
  }
  if (!copiedPopup) {
    const minimal = `<!doctype html><html><head><meta charset=\\"utf-8\\"><title>Popup</title></head><body><script type=\\"module\\" src=\\"popup.js\\"></script></body></html>`;
    const popupDestSrc = path.join(destRootSrc, 'popup.html');
    const popupDestLegacy = path.join(destRootLegacy, 'popup.html');
    fs.writeFileSync(popupDestSrc, minimal, 'utf8');
    fs.writeFileSync(popupDestLegacy, minimal, 'utf8');
  }
} catch (err) {
  console.warn('⚠️  Extension build asset copy failed:', err);
}
