/**
 * @fileoverview Extension configuration generated from environment variables.
 *
 * This file is auto-generated by scripts/generate-config.js
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To update these values:
 * 1. Set environment variables: NEXT_PUBLIC_BACKEND_URL and EXTENSION_SHARED_SECRET
 * 2. Run: npm run build:ext
 */

/** Backend URL for API requests */
export const BACKEND_URL =
  'https://bluesky-card-cast-extension-8u6iubpsm-chejholloway1s-projects.vercel.app';

/** Shared secret for authenticating extension requests */
export const EXTENSION_SHARED_SECRET =
  'PHmqQj/o6pl0/7EN1+a1489n5DXvdLo3cs0tAbGoQAs=';
